//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionRecord
    {
        public int recordId { get; set; }
        public int adminId { get; set; }
        public int userId { get; set; }
        public byte[] actionTime { get; set; }
        public int actionId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
