//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser_Source
    {
        public int usersourceId { get; set; }
        public int UserId { get; set; }
        public int souceId { get; set; }
        public Nullable<System.DateTime> subscribeTime { get; set; }
    
        public virtual Source Source { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
