
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IdentityTest2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser_Source
{

    public int usersourceId { get; set; }

    public int UserId { get; set; }

    public int souceId { get; set; }

    public Nullable<System.DateTime> subscribeTime { get; set; }



    public virtual Source Source { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }

}

}
