
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IdentityTest2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser_Category
{

    public int usercategoryId { get; set; }

    public int userId { get; set; }

    public int categoryId { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual Category Category { get; set; }

}

}
