
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IdentityTest2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment1
{

    public int commentId { get; set; }

    public int userId { get; set; }

    public int newsId { get; set; }

    public byte[] postTime { get; set; }

    public string commentContent { get; set; }

    public bool isDisplayed { get; set; }

    public Nullable<int> numOfComentLikes { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual News1 News1 { get; set; }

}

}
