//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPasswordRequest
    {
        public System.Guid ResetId { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<System.DateTime> ResetRequestDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
