
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IdentityTest2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ResetPasswordRequest
{

    public System.Guid ResetId { get; set; }

    public Nullable<int> Id { get; set; }

    public Nullable<System.DateTime> ResetRequestDateTime { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
