
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IdentityTest2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User_Source1
{

    public int userId { get; set; }

    public string sourceName { get; set; }

    public int subscribeId { get; set; }

    public byte[] subscribeTime { get; set; }



    public virtual Source1 Source1 { get; set; }

    public virtual User User { get; set; }

}

}
