
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IdentityTest2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.ActionRecords = new HashSet<ActionRecord>();

        this.ActionRecords1 = new HashSet<ActionRecord>();

        this.Comments = new HashSet<Comment>();

        this.User_Category = new HashSet<User_Category>();

        this.User_Source = new HashSet<User_Source>();

    }


    public int userId { get; set; }

    public string userName { get; set; }

    public string userEmail { get; set; }

    public string password { get; set; }

    public Nullable<bool> isActive { get; set; }

    public Nullable<int> roleId { get; set; }

    public Nullable<int> notifyFrequency { get; set; }

    public Nullable<bool> isNotified { get; set; }

    public Nullable<int> selectedCategoryId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ActionRecord> ActionRecords { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ActionRecord> ActionRecords1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comment> Comments { get; set; }

    public virtual Role Role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User_Category> User_Category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User_Source> User_Source { get; set; }

}

}
